"""Subset simulation, an independent second opinion on any failure probability.

    Au and Beck, "Estimation of small failure probabilities in high dimensions
    by subset simulation", Probabilistic Engineering Mechanics 16(4):263-277,
    2001

which is reference [13] of the Safe-ICE paper, and the method that paper used
to obtain its heat-transfer reference value.

This is not importance sampling. Rather than reweighting samples from a fitted
proposal, it factorises the rare event into a chain of nested ones that are each
easy to reach:

.. math::

    P_F = \\mathbb{P}(F_1) \\prod_{i=2}^{m} \\mathbb{P}(F_i \\mid F_{i-1})

where :math:`F_1 \\supset F_2 \\supset \\dots \\supset F_m = F` are defined by a
falling sequence of thresholds on ``g``. Each threshold is chosen so that a
fixed fraction ``p0`` of the current samples pass it, which makes every
conditional probability equal to ``p0`` by construction, and the conditional
samples for the next level are generated by Markov chain Monte Carlo seeded
from the ones that passed.

Sharing nothing with the importance-sampling machinery is the point. Two
methods that share an implementation can be wrong together; this one uses no
proposal distribution, no mixture, no importance weights and no EM step, so
agreement between it and Safe-ICE is evidence about the answer rather than
about the code.
"""

from __future__ import annotations

from typing import Any

import numpy as np
from scipy import stats

from ..typing import LimitStateFunction, NDArrayF


class SubsetSimulation:
    """Estimate a failure probability by subset simulation.

    Parameters
    ----------
    limit_state_function:
        Function g(u) such that failure occurs when g(u) <= 0.
    dimension:
        Problem dimension.
    N:
        Samples per level.
    p0:
        Conditional probability per level. Each threshold is set so that this
        fraction of the current samples pass, so the number of levels needed is
        about ``log(P_F) / log(p0)``. Au and Beck recommend 0.1, which balances
        the number of levels against the correlation of the chains within one.
        ``N * p0`` must be a whole number of seeds.
    max_levels:
        Give up after this many levels. Reaching it means ``P_F`` is smaller
        than ``p0 ** max_levels`` or the chains are not mixing.
    proposal_std:
        Standard deviation of the component-wise random-walk proposal used
        inside a level. One is a reasonable default for a standard normal
        target: much smaller and the chains barely move, much larger and almost
        every candidate is rejected.
    random_state:
        Seed or generator, for reproducibility.

    Notes
    -----
    The estimate is unbiased only in the limit; for finite ``N`` it carries a
    small bias because the thresholds are estimated from the same samples used
    to estimate the conditional probabilities. The coefficient of variation
    reported in the results treats the levels as independent, which understates
    it, since the chains within a level are correlated. Both are properties of
    the method rather than of this implementation.
    """

    def __init__(
        self,
        limit_state_function: LimitStateFunction,
        dimension: int,
        N: int = 1000,
        p0: float = 0.1,
        max_levels: int = 20,
        proposal_std: float = 1.0,
        random_state: int | np.random.Generator | None = None,
    ) -> None:
        self.g = limit_state_function
        self.d = int(dimension)
        self.N = int(N)
        self.p0 = float(p0)
        self.max_levels = int(max_levels)
        self.proposal_std = float(proposal_std)

        if not 0.0 < self.p0 < 1.0:
            raise ValueError(f"p0 must lie strictly between 0 and 1, got {self.p0}.")

        n_seeds = self.p0 * self.N
        if not float(n_seeds).is_integer() or n_seeds < 1:
            raise ValueError(
                f"p0 * N must be a positive whole number of seeds, got {n_seeds}."
            )
        if self.N % int(n_seeds) != 0:
            # Each seed starts a chain of equal length, so the seeds have to
            # divide N. p0=0.15 with N=1000 gives 150 whole seeds but chains of
            # 6 steps, which fills only 900 of the 1000 places.
            raise ValueError(
                f"N must be a whole number of chains: {self.N} places cannot be "
                f"filled evenly by {int(n_seeds)} seeds."
            )

        self._n_seeds = int(n_seeds)
        self._steps_per_seed = self.N // self._n_seeds

        if random_state is None:
            self._rng: Any = np.random.default_rng()
        elif isinstance(random_state, np.random.Generator):
            self._rng = random_state
        else:
            self._rng = np.random.default_rng(int(random_state))

    # -------------------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------------------
    def run(self, verbose: bool = True) -> tuple[float, dict[str, Any]]:
        """Estimate the failure probability.

        Returns
        -------
        tuple
            The estimate, and a dictionary of diagnostics. ``levels`` holds one
            record per level with its threshold and conditional probability.
        """
        samples: NDArrayF = np.asarray(
            self._rng.standard_normal((self.N, self.d)), dtype=np.float64
        )
        g_values = self._evaluate(samples)

        levels: list[dict[str, float]] = []
        conditional_probabilities: list[float] = []

        if verbose:
            print("=" * 56)
            print("Subset simulation")
            print(f"  dimension {self.d}, {self.N} samples per level, p0 = {self.p0}")
            print("=" * 56)

        for level in range(self.max_levels):
            order = np.argsort(g_values)
            samples, g_values = samples[order], g_values[order]

            # The p0-quantile of g. Failure is g <= 0, so a threshold at or
            # below zero means this level already reaches the real failure set.
            threshold = float(g_values[self._n_seeds - 1])
            final_level = threshold <= 0.0
            if final_level:
                threshold = 0.0

            # p0 exactly at an intermediate level: the threshold is defined as
            # the p0-quantile, so that fraction passes by construction. Counting
            # `g <= threshold` instead would drift above p0, because rejected
            # MCMC moves leave duplicate states and a duplicate sitting on the
            # threshold is counted too. That bias compounds over levels -- 0.5%
            # per level is 3% over six of them, all in the same direction.
            conditional = (
                float(np.mean(g_values <= threshold)) if final_level else self.p0
            )
            levels.append(
                {
                    "level": float(level),
                    "threshold": threshold,
                    "conditional_probability": conditional,
                    "final": float(final_level),
                }
            )
            conditional_probabilities.append(conditional)

            if verbose:
                print(
                    f"  level {level}: threshold {threshold:+.4g}  "
                    f"conditional {conditional:.4g}"
                    + ("   (reaches the failure set)" if final_level else "")
                )

            if final_level:
                break

            seeds = samples[: self._n_seeds]
            seed_g = g_values[: self._n_seeds]
            samples, g_values = self._conditional_samples(seeds, seed_g, threshold)

        pf = float(np.prod(conditional_probabilities))

        results: dict[str, Any] = {
            "failure_probability": pf,
            "levels": levels,
            "n_levels": len(levels),
            "conditional_probabilities": conditional_probabilities,
            "final_samples": samples,
            "final_g_values": g_values,
            "n_evaluations": self.N * len(levels),
            "reached_failure_set": bool(levels[-1]["final"]),
        }

        if verbose:
            print("-" * 56)
            print(f"Failure probability: {pf:.6e}")
            print(f"Levels: {len(levels)}   evaluations: {results['n_evaluations']:,}")
            if not results["reached_failure_set"]:
                print(
                    "WARNING: stopped before reaching g <= 0; estimate is an upper bound"
                )

        return pf, results

    # -------------------------------------------------------------------------
    # Internals
    # -------------------------------------------------------------------------
    def _evaluate(self, samples: NDArrayF) -> NDArrayF:
        """Evaluate g on a batch, falling back to row-wise if needed."""
        try:
            values = np.asarray(self.g(samples), dtype=np.float64).reshape(-1)
            if values.shape[0] != samples.shape[0]:
                raise ValueError("limit-state output shape mismatch")
        except (ValueError, TypeError, IndexError):
            values = np.array(
                [float(np.asarray(self.g(row)).reshape(-1)[0]) for row in samples],
                dtype=np.float64,
            )
        return np.where(np.isnan(values), np.inf, values)

    def _conditional_samples(
        self, seeds: NDArrayF, seed_g: NDArrayF, threshold: float
    ) -> tuple[NDArrayF, NDArrayF]:
        """Populate the next level by MCMC from the samples that passed.

        The modified Metropolis algorithm of Au and Beck: each component is
        proposed and accepted against its own standard normal marginal, and the
        assembled candidate is then kept only if it stays inside the current
        level. Treating the components separately is what keeps the acceptance
        rate from collapsing as the dimension grows, which is the reason plain
        Metropolis-Hastings is unusable here.
        """
        chains = seeds.shape[0]
        states = seeds.copy()
        state_g = seed_g.copy()

        collected = [states.copy()]
        collected_g = [state_g.copy()]

        for _ in range(self._steps_per_seed - 1):
            proposals = states + self.proposal_std * np.asarray(
                self._rng.standard_normal((chains, self.d)), dtype=np.float64
            )

            # Component-wise acceptance against the standard normal marginal.
            log_ratio = stats.norm.logpdf(proposals) - stats.norm.logpdf(states)
            accept_component = np.log(
                np.asarray(self._rng.uniform(size=(chains, self.d)), dtype=np.float64)
            ) < np.minimum(log_ratio, 0.0)
            candidates = np.where(accept_component, proposals, states)

            candidate_g = self._evaluate(candidates)

            # Keep the candidate only if it remains in the current level.
            inside = candidate_g <= threshold
            states = np.where(inside[:, None], candidates, states)
            state_g = np.where(inside, candidate_g, state_g)

            collected.append(states.copy())
            collected_g.append(state_g.copy())

        samples = np.vstack(collected)
        g_values = np.concatenate(collected_g)
        return samples[: self.N], g_values[: self.N]
